[package]
name = "gol"
version = "0.1.0"
authors = ["Patrik <patrik.stas@absa.africa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
pancurses = "0.16.1"